spring:
  application:
    name: sample-bank-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: sample-bank-app

logging:
  level:
    root: INFO
observability:
  logging:
    endpoint: http://localhost:8090/api/v1/logs